---
title: "Bayesian_models_exp2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}


dat <- read.csv("data20180719.csv")

####### test data 

dat <- subset(dat,human_id == "QSuzBXpbyRc370HsAACW")




#######

dat <- as_tibble(dat) %>% group_by(human_id,game)
dat <- dat %>%
  mutate(ai_action_prev = lag(ai_action,1), human_action_prev = lag(human_action,1))

```

```{r}
## the following computes probabilities of ai actions assuming
## strategy is always followed. (level refers to ai level)

## level 0 predictions
dat <- dat %>% mutate(pred_a1_level0 = case_when(
  game == "rps" & ai_action_prev == "rock" ~ 1,
  game == "fwg" & ai_action_prev == "fire" ~ 1,
  game == "numbers" & ai_action_prev == "one" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a2_level0 = case_when(
  game == "rps" & ai_action_prev == "paper" ~ 1,
  game == "fwg" & ai_action_prev == "water" ~ 1,
  game == "numbers" & ai_action_prev == "two" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a3_level0 = case_when(
  game == "rps" & ai_action_prev == "scissors" ~ 1,
  game == "fwg" & ai_action_prev == "grass" ~ 1,
  game == "numbers" & ai_action_prev == "three" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a4_level0 = case_when(
  game == "numbers" & ai_action_prev == "four" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))
dat <- dat %>% mutate(pred_a5_level0 = case_when(
  game == "numbers" & ai_action_prev == "five" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))

## level 1 predictions
dat <- dat %>% mutate(pred_a1_level1 = case_when(
  game == "rps" & human_action_prev == "scissors" ~ 1,
  game == "fwg" & human_action_prev == "grass" ~ 1,
  game == "numbers" & human_action_prev == "five" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a2_level1 = case_when(
  game == "rps" & human_action_prev == "rock" ~ 1,
  game == "fwg" & human_action_prev == "fire" ~ 1,
  game == "numbers" & human_action_prev == "one" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a3_level1 = case_when(
  game == "rps" & human_action_prev == "paper" ~ 1,
  game == "fwg" & human_action_prev == "water" ~ 1,
  game == "numbers" & ai_action_prev == "two" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a4_level1 = case_when(
  game == "numbers" & ai_action_prev == "three" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))
dat <- dat %>% mutate(pred_a5_level1 = case_when(
  game == "numbers" & ai_action_prev == "four" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))

## level 2 predictions
dat <- dat %>% mutate(pred_a1_level2 = case_when(
  game == "rps" & ai_action_prev == "paper" ~ 1,
  game == "fwg" & ai_action_prev == "water" ~ 1,
  game == "numbers" & ai_action_prev == "four" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a2_level2 = case_when(
  game == "rps" & ai_action_prev == "scissors" ~ 1,
  game == "fwg" & ai_action_prev == "grass" ~ 1,
  game == "numbers" & ai_action_prev == "five" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a3_level2 = case_when(
  game == "rps" & ai_action_prev == "rock" ~ 1,
  game == "fwg" & ai_action_prev == "fire" ~ 1,
  game == "numbers" & ai_action_prev == "one" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a4_level2 = case_when(
  game == "numbers" & ai_action_prev == "two" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))
dat <- dat %>% mutate(pred_a5_level2 = case_when(
  game == "numbers" & ai_action_prev == "three" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))



dat$ai_action_num <- recode(dat$ai_action,"rock" = 1, "paper" = 2, "scissors" = 3, "fire" = 1, "water" = 2, "grass" = 3, "one" = 1, "two" = 2, "three" = 3, "four" = 4 , "five" = 5)
dat$human_action_num <- recode(dat$human_action,"rock" = 1, "paper" = 2, "scissors" = 3, "fire" = 1, "water" = 2, "grass" = 3, "one" = 1, "two" = 2, "three" = 3, "four" = 4 , "five" = 5)

```

```{r}
# group data by subjective component id


# if human generalizes over games, we can run update the prior generally
# if human does not generalize, we need to reset the prior at the start of each ?stage?
exp1_Bayes_model_LL <- function(par,data, generalize = c("game","no"), return_value = "-2loglik") {
   # return_value=c("-2loglik","likelihood_by_trial")
  # data is a subset for a single participant
  generalize <- match.arg(generalize)
  alpha <- par[1] # probability that ai opponent plays according to strategy
  if(length(par) > 1) {
    beta <- par[2] # probability that human plays according to best response 
  } else{
    beta <- 1 # probability that human plays according to best response 
  }
  
  prior <- c(1,1,1) # prior alpha for dirichlet on p(level)
  prior <- prior/sum(prior)
  
  # use alpha to change the "deterministic" prediction
    
  dat <- ungroup(data) %>%
     mutate_at(.vars = vars(c(starts_with("pred_a1"),starts_with("pred_a2"),starts_with("pred_a3"))), 
                            funs (case_when(
      game == "numbers" ~  alpha*. + (1-alpha)/5,
                  TRUE ~ alpha*. + (1-alpha)/3))) %>%
     mutate_at(.vars = vars(c(starts_with("pred_a4"),starts_with("pred_a5"))), 
                            funs (case_when(
      game == "numbers" ~  alpha*. + (1-alpha)/5,
                  TRUE ~ 0)))
  
  if(generalize == "no") {
    # group by game and stage
    dat <- group_by(dat,game,add=TRUE)
  }
  
  # compute likelihood of ai action
  dat <- dat %>%
    mutate(
      lik_level0 = case_when(
        ai_action_num == 1 ~ pred_a1_level0,
        ai_action_num == 2 ~ pred_a2_level0,
        ai_action_num == 3 ~ pred_a3_level0,
        ai_action_num == 4 ~ pred_a4_level0,
        ai_action_num == 5 ~ pred_a5_level0
      ),
      lik_level1 = case_when(
        ai_action_num == 1 ~ pred_a1_level1,
        ai_action_num == 2 ~ pred_a2_level1,
        ai_action_num == 3 ~ pred_a3_level1,
        ai_action_num == 4 ~ pred_a4_level1,
        ai_action_num == 5 ~ pred_a5_level1
      ),
      lik_level2 = case_when(
        ai_action_num == 1 ~ pred_a1_level2,
        ai_action_num == 2 ~ pred_a2_level2,
        ai_action_num == 3 ~ pred_a3_level2,
        ai_action_num == 4 ~ pred_a4_level2,
        ai_action_num == 5 ~ pred_a5_level2
      )
    )
  
  # use likelihood to compute the posterior predictive probability of each level
  dat <- dat %>%
    mutate(logpost_level0 = lag(log(prior[1]) + cumsum(log(lik_level0)),default=log(prior[1])),
           logpost_level1 = lag(log(prior[2]) + cumsum(log(lik_level1)),default=log(prior[2])),
           logpost_level2 = lag(log(prior[3]) + cumsum(log(lik_level2)),default=log(prior[3]))) %>%
    # you can add or subtract any constant from the log-likelihoods; this can aid in precision
    mutate(min = pmin(logpost_level0,logpost_level1, logpost_level2)) %>%
      mutate(normalize = exp(logpost_level0 - min) + exp(logpost_level1 - min) + exp(logpost_level2 - min)) %>%
        mutate(post_level0 = exp(logpost_level0 - min)/normalize,
               post_level1 = exp(logpost_level1 - min)/normalize,
               post_level2 = exp(logpost_level2 - min)/normalize)
  
   #cat(as.character(c(round(dat$post_level0,2), round(dat$post_level1,2), round(dat$post_level2,2)), "\n", "\n"))
  
  # use posterior predictive probability to predict probability of each ai and then human action
  # opp is ai and self is human player here
  dat <- dat %>%
    mutate(p_opp_a1 = post_level0*pred_a1_level0 + post_level1*pred_a1_level1 + post_level2*pred_a1_level2,
           p_opp_a2 = post_level0*pred_a2_level0 + post_level1*pred_a2_level1 + post_level2*pred_a2_level2,
           p_opp_a3 = post_level0*pred_a3_level0 + post_level1*pred_a3_level1 + post_level2*pred_a3_level2,
           p_opp_a4 = post_level0*pred_a4_level0 + post_level1*pred_a4_level1 + post_level2*pred_a4_level2,
           p_opp_a5 = post_level0*pred_a5_level0 + post_level1*pred_a5_level1 + post_level2*pred_a5_level2
    ) %>%
      mutate(p_self_a1 = case_when(
              game == "numbers" ~ (1-beta)*(1/3) + beta*p_opp_a5,
              TRUE ~ (1-beta)*(1/3) + beta*(p_opp_a3)
                ),
             p_self_a2 = case_when(
               game == "numbers" ~ (1-beta)*(1/3) + beta*p_opp_a1,
               TRUE ~ (1-beta)*(1/3) + beta*(p_opp_a1)
             ),
             p_self_a3 = case_when(
               game == "numbers" ~ (1-beta)*(1/3) + beta*p_opp_a2,
               TRUE ~ (1-beta)*(1/3) + beta*(p_opp_a2)
             ),
             p_self_a4 = case_when(
               game == "numbers" ~ (1-beta)*(1/3) + beta*p_opp_a3,
               TRUE ~ 0
             ),
             p_self_a5 = case_when(
               game == "numbers" ~ (1-beta)*(1/3) + beta*p_opp_a4,
               TRUE ~ 0
             )
        )
  
  # now finally compute the likelihood of human actions 
  dat <- dat %>% 
    mutate(
      loglik = case_when(
        human_action_num == 1 ~ log(p_self_a1),
        human_action_num == 2 ~ log(p_self_a2),
        human_action_num == 3 ~ log(p_self_a3),
        human_action_num == 4 ~ log(p_self_a4),
        human_action_num == 5 ~ log(p_self_a5))
    )
  
  #cat(as.character(exp(dat$loglik)), "\n", "\n")
  
  ret <- -2*sum(dat$loglik)
  if(return_value == "-2loglik") {
    if(is.infinite(ret) || is.nan(ret)) {
    return(1e+300)
    } else {
      return(ret)
    } 
  } else if ((return_value == "likelihood_by_trial")) {
    return(exp(dat$loglik))
  }
    

}

```

```{r}
exp1_Bayes_model_LL(0.4,data = dat, generalize = "no", "likelihood_by_trial")
```

```{r}
#PLot likelihood for first participant as function of parameter 

dat <- subset(dat, human_id == "QSuzBXpbyRc370HsAACW")
likelihoods <- list()
for (t in 1:95) {
  likelihoods[t] <- exp1_Bayes_model_LL(t/100,data = dat, generalize = "game")
}

jpeg(file="QSuzBXpbyRc370HsAACW.jpeg")
plot(unlist(likelihoods))
dev.off()


```

```{r, ECHO = FALSE}

library(DEoptim)

exp1_Bayes_game_Tr <- exp1_Bayes_no_Tr <- list()

# # USing DEOptim 
for(id in levels(dat$human_id)) {
  tdat <- subset(dat,human_id == id)
  ctrl <- DEoptim.control(NP = 20, itermax=50,parallelType = 1, packages = c("dplyr"))
  exp1_Bayes_game_Tr[[id]] <- DEoptim(exp1_Bayes_model_LL, lower=c(0), upper = c(1), data = tdat,
                                  generalize = "game",control=ctrl)
  exp1_Bayes_no_Tr[[id]] <- DEoptim(exp1_Bayes_model_LL, lower=c(0), upper = c(1), data = tdat,
                                  generalize = "no",control=ctrl)
}


# using optim


# for(id in levels(dat$human_id)) {
#   tdat <- subset(dat,human_id == id)
#   # ctrl <- DEoptim.control(NP = 20, itermax=50)
#   
#   Bayes_same_game[[id]] <- optim(c(0.1),fn=Bayes_model_LL,data=tdat, distinct_opponent = FALSE, 
#                                  generalize = "game", lower = c(0), upper = c(1),method="L-BFGS-B")
#   
#   
#   Bayes_same_stage[[id]] <- optim(c(0.1),fn=Bayes_model_LL,data=tdat, distinct_opponent = FALSE, 
#                                  generalize = "stage", lower = c(0), upper = c(1),method="L-BFGS-B")
# 
#   Bayes_same_no[[id]] <- optim(c(0.1),fn=Bayes_model_LL,data=tdat, distinct_opponent = FALSE, 
#                                  generalize = "no", lower = c(0), upper = c(1),method="L-BFGS-B")
# 
#   Bayes_distinct_game[[id]] <- optim(c(0.1),fn=Bayes_model_LL,data=tdat, distinct_opponent = TRUE, 
#                                  generalize = "game", lower = c(0), upper = c(1),method="L-BFGS-B")
# 
#   Bayes_distinct_stage[[id]] <- optim(c(0.1),fn=Bayes_model_LL,data=tdat, distinct_opponent = TRUE, 
#                                  generalize = "stage", lower = c(0), upper = c(1),method="L-BFGS-B")
# 
#   Bayes_distinct_no[[id]] <- optim(c(0.1),fn=Bayes_model_LL,data=tdat, distinct_opponent = TRUE, 
#                                  generalize = "no", lower = c(0), upper = c(1),method="L-BFGS-B")
# }
```
```{r}

exp1_Bayes_game_Tr[["QSuzBXpbyRc370HsAACW"]]$optim$bestval
exp1_Bayes_game_Tr[["QSuzBXpbyRc370HsAACW"]]$optim$bestmem[[1]]
```



