---
title: "exp1_lik_by_trial"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
```

```{r}
# Get Data for experiment 1, remove unecessary columns 

dat <- read.csv("data20180719.csv")
#####
# dat <- subset(dat, human_id == "38VxtUSv_h6RR5-tAAA2")
####

optim_results <- read.csv("exp1_all_results.csv")

```

```{r}

#preparing data for functions to claculate likelihood

# transform 'winner' variable in numeric score
dat$score <- recode(dat$winner, human = 1, tie = 0, ai = -1)
# create a new variable 'block' with round 1...25 = block 1 and round 26...50 as block 2
dat$block <- as.numeric(cut(dat$round,2))

# recode actions to make them equal to the codes in these files
dat$h_action <- recode(dat$human_action,"rock" = "R", "paper" = "P", "scissors" = "S", "fire" = "F", "water" = "W", "grass" = "G", "one" = "1", "two" = "2", "three" = "3", "four" = "4", "five" = "5")
dat$a_action <- recode(dat$ai_action,"rock" = "R", "paper" = "P", "scissors" = "S", "fire" = "F", "water" = "W", "grass" = "G", "one" = "1", "two" = "2", "three" = "3", "four" = "4", "five" = "5")



# Prepping data for Bayesian code
dat <- as_tibble(dat) %>% group_by(human_id,game)
dat <- dat %>%
  mutate(ai_action_prev = lag(ai_action,1), human_action_prev = lag(human_action,1))


## level 0 predictions
dat <- dat %>% mutate(pred_a1_level0 = case_when(
  game == "rps" & ai_action_prev == "rock" ~ 1,
  game == "fwg" & ai_action_prev == "fire" ~ 1,
  game == "numbers" & ai_action_prev == "one" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a2_level0 = case_when(
  game == "rps" & ai_action_prev == "paper" ~ 1,
  game == "fwg" & ai_action_prev == "water" ~ 1,
  game == "numbers" & ai_action_prev == "two" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a3_level0 = case_when(
  game == "rps" & ai_action_prev == "scissors" ~ 1,
  game == "fwg" & ai_action_prev == "grass" ~ 1,
  game == "numbers" & ai_action_prev == "three" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a4_level0 = case_when(
  game == "numbers" & ai_action_prev == "four" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))
dat <- dat %>% mutate(pred_a5_level0 = case_when(
  game == "numbers" & ai_action_prev == "five" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))

## level 1 predictions
dat <- dat %>% mutate(pred_a1_level1 = case_when(
  game == "rps" & human_action_prev == "scissors" ~ 1,
  game == "fwg" & human_action_prev == "grass" ~ 1,
  game == "numbers" & human_action_prev == "five" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a2_level1 = case_when(
  game == "rps" & human_action_prev == "rock" ~ 1,
  game == "fwg" & human_action_prev == "fire" ~ 1,
  game == "numbers" & human_action_prev == "one" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a3_level1 = case_when(
  game == "rps" & human_action_prev == "paper" ~ 1,
  game == "fwg" & human_action_prev == "water" ~ 1,
  game == "numbers" & ai_action_prev == "two" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a4_level1 = case_when(
  game == "numbers" & ai_action_prev == "three" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))
dat <- dat %>% mutate(pred_a5_level1 = case_when(
  game == "numbers" & ai_action_prev == "four" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))

## level 2 predictions
dat <- dat %>% mutate(pred_a1_level2 = case_when(
  game == "rps" & ai_action_prev == "paper" ~ 1,
  game == "fwg" & ai_action_prev == "water" ~ 1,
  game == "numbers" & ai_action_prev == "four" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a2_level2 = case_when(
  game == "rps" & ai_action_prev == "scissors" ~ 1,
  game == "fwg" & ai_action_prev == "grass" ~ 1,
  game == "numbers" & ai_action_prev == "five" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a3_level2 = case_when(
  game == "rps" & ai_action_prev == "rock" ~ 1,
  game == "fwg" & ai_action_prev == "fire" ~ 1,
  game == "numbers" & ai_action_prev == "one" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  is.na(ai_action_prev) ~ 1/3,
  !is.na(ai_action_prev) ~ 0))
dat <- dat %>% mutate(pred_a4_level2 = case_when(
  game == "numbers" & ai_action_prev == "two" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))
dat <- dat %>% mutate(pred_a5_level2 = case_when(
  game == "numbers" & ai_action_prev == "three" ~ 1,
  game == "numbers" & is.na(ai_action_prev) ~ 1/5,
  TRUE ~ 0))



dat$ai_action_num <- recode(dat$ai_action,"rock" = 1, "paper" = 2, "scissors" = 3, "fire" = 1, "water" = 2, "grass" = 3, "one" = 1, "two" = 2, "three" = 3, "four" = 4 , "five" = 5)
dat$human_action_num <- recode(dat$human_action,"rock" = 1, "paper" = 2, "scissors" = 3, "fire" = 1, "water" = 2, "grass" = 3, "one" = 1, "two" = 2, "three" = 3, "four" = 4 , "five" = 5)


```


```{r}

dat <- as.data.frame(dat)                       
exp1_lik_by_trial <- data.frame()

for(id in unique(dat$human_id)) {
  
  tdat <- dat %>% subset(human_id == id)
  
  # QLS likelihoods 
  pars_QLS <- unlist(filter(optim_results, ID == id)%>%select(QL_states_Beta,QL_states_alpha))
  QLS_lik <- Q_learn_states(pars_QLS ,tdat,"likelihood_by_trial",gamma = 0)
  
  # Bayes model no transfer likelihoods
  theta_NT <- unlist(filter(optim_results, ID == id)%>%select(theta_no_transfer))
  Bayes_NT_lik <- exp1_Bayes_model_LL(theta_NT ,tdat, generalize = "no", "likelihood_by_trial") 
  
  # Bayes model with Transfer likelihood
  theta_Tr <- unlist(filter(optim_results, ID == id)%>%select(theta_transfer))
  Bayes_Tr_lik <- exp1_Bayes_model_LL(theta_Tr ,data = tdat, generalize = "game", "likelihood_by_trial") 
  
  
  exp1_lik_by_trial <- rbind(exp1_lik_by_trial,
                        data.frame(
                          "human_id" = id,
                          "condition" = dat$condition,
                          "game" = dat$game,
                          "round" = dat$round,
                          "QLS_lik" = QLS_lik,
                          "Bayes_NT_lik" = Bayes_NT_lik,
                          "Bayes_Tr_lik" = Bayes_Tr_lik
                          
                        ))
}

```

```{r}

which(exp1_lik_by_trial$QLS_lik == 1.0 )


```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)


mean_lik <- exp1_lik_by_trial %>%
  select(human_id,condition,game, round,QLS_lik,Bayes_NT_lik,Bayes_Tr_lik) %>%
  group_by(condition,game,round) %>%
  summarise(mean_QLS_lik = mean(QLS_lik, na.rm = TRUE),
            mean_NT_lik = mean(Bayes_NT_lik, na.rm = TRUE),
            mean_Tr_lik = mean(Bayes_Tr_lik, na.rm = TRUE))

mean_lik$game <- factor(mean_lik$game,levels=c("rps","fwg","numbers"))

data_long <- gather(mean_lik, strategy, probability, mean_QLS_lik:mean_Tr_lik, factor_key=TRUE)

# make sure the different games are ordered in the way they were played
data_long$game <- factor(data_long$game,levels=c("rps","fwg","numbers"))
ggplot(data_long,aes(x=round,y=probability,colour=strategy)) + geom_line() + facet_grid(game~condition)


```

